name: flix_id
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.13.6
  dio: ^5.4.0
  email_validator: ^2.1.17
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.9
  flutter_riverpod: ^2.4.9
  flutter_typeahead: ^5.0.2
  freezed_annotation: ^2.4.1
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.6
  intl: ^0.18.1
  json_annotation: ^4.8.1
  path: ^1.8.3
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/flix_logo_splash.png"
  adaptive_icon_background: "#1F1D2B"
  adaptive_icon_foreground: "assets/flix_icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
